### ISSUE TITLE
False negatives in determining insiders

### ISSUE THREAD

**Issue by PiotrZakrzewski** [PiotrZakrzewski/merge-chance#3]
Some projects have regular contributors or even maintainers who are not officially part of their GitHub org.
This skews the merge chance much higher in two-fold:
- such users make many PRs
- their PRs have structurally higher merge-chance and lower median time to close
They should be excluded, as merge-chance is intended to measure an outsider stats.

Proposed design to address this issue:
- agree on number of PRs a nominal outsider (someone with an `authorAffiliation` suggesting outsider status) needs to merge among recent PRs to be consider an insider. Lets say 5.
- filter out such PRs, just like the other insiders

This would be implemented in a v2 badge endpoint so as to not force existing users onto a new methodology unexpectedly.

**Comment by wardweistra** [comment]
Your comments here are insightful: https://github.com/RIOT-OS/RIOT/pull/15737#issuecomment-759627472. If indeed the contributors status with the PR comes from the membership status at PR time, perhaps you can request current affiliations of a user and rely on that instead?

Another thing I worry about, where it relies on membership of the org owning the repo: being a member of an org you have to explicitly choose to be visible as a org member. Perhaps if you haven't done so Github won't expose in your PR either that you are?

If you're taking a >X number of PRs as an insider, you probably want to specify >X PRs per time unit. I know that's tough with your current 'last 300 PRs' but otherwise it's an arbitrary metric benefiting large repos (more PRs means less chance the hidden insider is counted as such)

**Comment by PiotrZakrzewski** [comment]
The proposed solution is now deployed at https://acceptance.merge-chance.info

**Comment by PiotrZakrzewski** [comment]
> Your comments here are insightful: [RIOT-OS/RIOT#15737 (comment)](https://github.com/RIOT-OS/RIOT/pull/15737#issuecomment-759627472). If indeed the contributors status with the PR comes from the membership status at PR time, perhaps you can request current affiliations of a user and rely on that instead?
> 
> Another thing I worry about, where it relies on membership of the org owning the repo: being a member of an org you have to explicitly choose to be visible as a org member. Perhaps if you haven't done so Github won't expose in your PR either that you are?
> 
> If you're taking a >X number of PRs as an insider, you probably want to specify >X PRs per time unit. I know that's tough with your current 'last 300 PRs' but otherwise it's an arbitrary metric benefiting large repos (more PRs means less chance the hidden insider is counted as such)

I reimplemented way the data is fetched to avoid bias big projects can bring. Now I keep fetching data until I gather enough PRs (50) that are classified as outsiders (with correction for implied insiders). That significantly increases the rate-limiting cost of the query but I think it is worth it.
